/**
 * Adds Amharic translations to all departments in the database.
 * Run: node src/utils/seedDepartmentAmharic.js
 */
require("dotenv").config({ path: require("path").join(__dirname, "../../.env") });
const mongoose = require("mongoose");
const Department = require("../models/Department");

const amharicData = [
  // SECTOR 1: Executive Leadership
  { id: 1,
    name: { en: "Minister's Office", am: "የሚኒስትሩ ቢሮ" },
    description: { en: "Executive leadership overseeing all ministry operations and strategic direction.", am: "ሁሉንም የሚኒስቴሩ ሥራዎች እና ስትራቴጂካዊ አቅጣጫ የሚቆጣጠር ሥራ አስፈጻሚ አመራር።" },
    directions: { en: "Take elevator to Floor 7. Minister's office is straight ahead from elevator. Room 701 with green door.", am: "ሊፍት ወደ 7ኛ ፎቅ ይውሰዱ። የሚኒስትሩ ቢሮ ከሊፍቱ ቀጥታ ወደፊት ነው። ክፍል 701 አረንጓዴ በር ያለው።" },
    services: { en: ["Executive decision making", "Policy approval", "Strategic guidance", "Ministerial correspondence"], am: ["ሥራ አስፈጻሚ ውሳኔ አሰጣጥ", "የፖሊሲ ማፅደቅ", "ስትራቴጂካዊ ሀሳብ", "የሚኒስቴር ደብዳቤ"] },
  },
  { id: 2,
    name: { en: "Deputy Minister Office", am: "የምክትል ሚኒስትሩ ቢሮ" },
    description: { en: "Deputy minister's office supporting ministerial operations.", am: "የሚኒስቴሩ ሥራዎችን የሚደግፍ የምክትል ሚኒስትሩ ቢሮ።" },
    directions: { en: "Take elevator to Floor 6. Deputy office is first door on right.", am: "ሊፍት ወደ 6ኛ ፎቅ ይውሰዱ። የምክትሉ ቢሮ በቀኝ በኩል የመጀመሪያው ክፍል ነው።" },
    services: { en: ["Policy coordination", "Strategic planning", "Inter-ministerial relations"], am: ["የፖሊሲ ቅንጅት", "ስትራቴጂካዊ ዕቅድ", "ከሌሎች ሚኒስቴሮች ጋር ግንኙነት"] },
  },
  { id: 3,
    name: { en: "Leadership Chief Executive", am: "የዋና ሥራ አስፈጻሚ ቢሮ" },
    description: { en: "Chief executive overseeing daily ministry operations.", am: "ዕለታዊ የሚኒስቴሩ ሥራዎችን የሚቆጣጠር ዋና ሥራ አስፈጻሚ።" },
    directions: { en: "Take elevator to Floor 4. Room 401 at the end of corridor.", am: "ሊፍት ወደ 4ኛ ፎቅ ይውሰዱ። ክፍል 401 በኮሪደሩ መጨረሻ ላይ ነው።" },
    services: { en: ["Operational management", "Executive coordination", "Strategic execution"], am: ["የሥራ ሂደት አስተዳደር", "ሥራ አስፈጻሚ ቅንጅት", "ስትራቴጂካዊ አፈፃፀም"] },
  },
  { id: 4,
    name: { en: "Strategic Affairs Executive", am: "የስትራቴጂ ጉዳዮች ሥራ አስፈጻሚ" },
    description: { en: "Strategic planning and coordination of ministry initiatives.", am: "ስትራቴጂካዊ ዕቅድ እና የሚኒስቴሩ ተነሳሽነቶች ቅንጅት።" },
    directions: { en: "Take elevator to Floor 3, turn right. Room 310 is third door.", am: "ሊፍት ወደ 3ኛ ፎቅ ይውሰዱ፣ ወደ ቀኝ ይታጠፉ። ክፍል 310 ሦስተኛው ክፍል ነው።" },
    services: { en: ["Strategic planning", "Policy coordination", "Performance monitoring"], am: ["ስትራቴጂካዊ ዕቅድ", "የፖሊሲ ቅንጅት", "የአፈፃፀም ክትትል"] },
  },
  { id: 5,
    name: { en: "Basic Service Executive", am: "የመሠረታዊ አገልግሎት ሥራ አስፈጻሚ" },
    description: { en: "Basic service delivery coordination.", am: "የመሠረታዊ አገልግሎት አሰጣጥ ቅንጅት።" },
    directions: { en: "Take elevator to Floor 3. Room 311 is across from Strategic Affairs.", am: "ሊፍት ወደ 3ኛ ፎቅ ይውሰዱ። ክፍል 311 ከስትራቴጂ ጉዳዮች ሥራ አስፈጻሚ ፊት ለፊት ነው።" },
    services: { en: ["Service delivery", "Citizen support", "Complaint handling"], am: ["አገልግሎት አሰጣጥ", "የዜጎች ድጋፍ", "ቅሬታ አስተናጋጅ"] },
  },
  { id: 6,
    name: { en: "Minister's Secretariat", am: "የሚኒስትሩ ጽሕፈት ቤት" },
    description: { en: "Minister's office administration and coordination.", am: "የሚኒስቴሩ ቢሮ አስተዳደር እና ቅንጅት።" },
    directions: { en: "Take elevator to Floor 2. Room 203 at the end of corridor.", am: "ሊፍት ወደ 2ኛ ፎቅ ይውሰዱ። ክፍል 203 በኮሪደሩ መጨረሻ ላይ ነው።" },
    services: { en: ["Meeting coordination", "Document management", "Schedule management"], am: ["የስብሰባ ቅንጅት", "ሰነድ አስተዳደር", "የጊዜ ሰሌዳ አስተዳደር"] },
  },
  // SECTOR 2: Innovation & Technology
  { id: 7,
    name: { en: "Technology Center", am: "የቴክኖሎጂ ማዕከል" },
    description: { en: "Technology innovation, incubation, and research center.", am: "የቴክኖሎጂ ፈጠራ፣ ኢንኩቤሽን እና ምርምር ማዕከል።" },
    directions: { en: "Take elevator to Floor 1, turn right. Room 101-102 is first door. Green door with 'Technology Center' sign.", am: "ሊፍት ወደ 1ኛ ፎቅ ይውሰዱ፣ ወደ ቀኝ ይታጠፉ። ክፍል 101-102 የመጀመሪያው ክፍል ነው። 'የቴክኖሎጂ ማዕከል' የሚል ምልክት ያለው አረንጓዴ በር።" },
    services: { en: ["Technology incubation", "Innovation consulting", "Startup mentorship", "Tech research"], am: ["የቴክኖሎጂ ኢንኩቤሽን", "የፈጠራ ምክርና ድጋፍ", "ለስታርተፖች አማካሪነት", "የቴክኖሎጂ ምርምር"] },
  },
  { id: 8,
    name: { en: "Innovation Fund Office", am: "የፈጠራ ፈንድ ቢሮ" },
    description: { en: "Funding and grants for innovation projects.", am: "ለፈጠራ ፕሮጀክቶች የሚሰጥ ፋይናንስ እና ድጋፍ።" },
    directions: { en: "Take elevator to Floor 2, turn left. Room 202 is second door.", am: "ሊፍት ወደ 2ኛ ፎቅ ይውሰዱ፣ ወደ ግራ ይታጠፉ። ክፍል 202 ሁለተኛው ክፍል ነው።" },
    services: { en: ["Grant applications", "Innovation funding", "Startup investment", "Project evaluation"], am: ["የድጋፍ ማመልከቻ", "የፈጠራ ፋይናንስ", "ለስታርተፖች ኢንቨስትመንት", "የፕሮጀክት ግምገማ"] },
  },
  { id: 9,
    name: { en: "Technology Development & Transfer", am: "የቴክኖሎጂ ልማት እና ሽግግር" },
    description: { en: "Technology development and transfer to industry.", am: "ወደ ኢንዱስትሪ የቴክኖሎጂ ልማት እና ሽግግር።" },
    directions: { en: "Take elevator to Floor 5, turn right. Room 501 at the end.", am: "ሊፍት ወደ 5ኛ ፎቅ ይውሰዱ፣ ወደ ቀኝ ይታጠፉ። ክፍል 501 በመጨረሻ ላይ ነው።" },
    services: { en: ["Tech transfer", "Industry partnership", "Technology commercialization", "R&D coordination"], am: ["የቴክኖሎጂ ሽግግር", "ከኢንዱስትሪ ጋር ሽርክና", "የቴክኖሎጂ ግብይት", "R&D ቅንጅት"] },
  },
  { id: 10,
    name: { en: "Startup", am: "ስታርተፕ" },
    description: { en: "Startup support, incubation, and acceleration programs.", am: "ለስታርተፖች ድጋፍ፣ ኢንኩቤሽን እና ፍጥነት ማስጨበጫ ፕሮግራሞች።" },
    directions: { en: "Take elevator to Floor 6. Room 602 is near the elevator.", am: "ሊፍት ወደ 6ኛ ፎቅ ይውሰዱ። ክፍል 602 ከሊፍቱ አጠገብ ነው።" },
    services: { en: ["Startup incubation", "Mentorship", "Networking events", "Pitch training"], am: ["ስታርተፕ ኢንኩቤሽን", "አማካሪነት", "የኔትወርኪንግ ዝግጅቶች", "ፒቺንግ ሥልጠና"] },
  },
  { id: 11,
    name: { en: "Innovation & Technology Cooperation", am: "የፈጠራ እና ቴክኖሎጂ ትብብር" },
    description: { en: "International cooperation and partnership coordination.", am: "ዓለም አቀፍ ትብብር እና ሽርክና ቅንጅት።" },
    directions: { en: "Take elevator to Floor 5. Room 502 next to Technology Development.", am: "ሊፍት ወደ 5ኛ ፎቅ ይውሰዱ። ክፍል 502 ከቴክኖሎጂ ልማት አጠገብ ነው።" },
    services: { en: ["International partnership", "Knowledge exchange", "Collaboration programs"], am: ["ዓለም አቀፍ ሽርክና", "የዕውቀት ልውውጥ", "የትብብር ፕሮግራሞች"] },
  },
  { id: 12,
    name: { en: "Research & Development", am: "ምርምር እና ልማት" },
    description: { en: "National research and development coordination.", am: "ብሔራዊ ምርምር እና ልማት ቅንጅት።" },
    directions: { en: "Take elevator to Floor 5, turn left. Room 503 at the end.", am: "ሊፍት ወደ 5ኛ ፎቅ ይውሰዱ፣ ወደ ግራ ይታጠፉ። ክፍል 503 በመጨረሻ ላይ ነው።" },
    services: { en: ["Research coordination", "Grant management", "Research evaluation", "Publication support"], am: ["የምርምር ቅንጅት", "የድጋፍ አስተዳደር", "የምርምር ግምገማ", "የህትመት ድጋፍ"] },
  },
  // SECTOR 3: Finance & Administration
  { id: 13,
    name: { en: "Treasury & Finance Office", am: "የግምጃ ቤት እና ፋይናንስ ቢሮ" },
    description: { en: "Budget management and financial operations.", am: "የበጀት አስተዳደር እና የፋይናንስ ሥራዎች።" },
    directions: { en: "Take elevator to Floor 3, turn left. Room 301 is first door.", am: "ሊፍት ወደ 3ኛ ፎቅ ይውሰዱ፣ ወደ ግራ ይታጠፉ። ክፍል 301 የመጀመሪያው ክፍል ነው።" },
    services: { en: ["Budget planning", "Financial reporting", "Payment processing", "Expense tracking"], am: ["የበጀት ዕቅድ", "የፋይናንስ ሪፖርት", "ክፍያ ሂደት", "ወጪ ክትትል"] },
  },
  { id: 14,
    name: { en: "Procurement & Finance Executive", am: "የግዥ እና ፋይናንስ ሥራ አስፈጻሚ" },
    description: { en: "Government procurement and contract management.", am: "የመንግሥት ግዥ እና ውል አስተዳደር።" },
    directions: { en: "Take elevator to Floor 4, turn right. Room 402 is second door.", am: "ሊፍት ወደ 4ኛ ፎቅ ይውሰዱ፣ ወደ ቀኝ ይታጠፉ። ክፍል 402 ሁለተኛው ክፍል ነው።" },
    services: { en: ["Tender management", "Vendor registration", "Contract awards", "Supplier evaluation"], am: ["ጨረታ አስተዳደር", "አቅራቢ ምዝገባ", "ውል አሸናፊ ማወጅ", "አቅራቢ ግምገማ"] },
  },
  { id: 15,
    name: { en: "Audit Office Executive", am: "የኦዲት ቢሮ ሥራ አስፈጻሚ" },
    description: { en: "Internal audit and compliance monitoring.", am: "ውስጣዊ ኦዲት እና ተገዢነት ክትትል።" },
    directions: { en: "Take elevator to Floor 2. Room 201 is first door on left.", am: "ሊፍት ወደ 2ኛ ፎቅ ይውሰዱ። ክፍል 201 በግራ በኩል የመጀመሪያው ክፍል ነው።" },
    services: { en: ["Internal audit", "Compliance review", "Risk assessment", "Financial audit"], am: ["ውስጣዊ ኦዲት", "ተገዢነት ግምገማ", "ስጋት ምዘና", "የፋይናንስ ኦዲት"] },
  },
  // SECTOR 4: Policy & Strategy
  { id: 16,
    name: { en: "Policy & Strategic Affairs", am: "ፖሊሲ እና ስትራቴጂካዊ ጉዳዮች" },
    description: { en: "Policy development and strategic planning.", am: "የፖሊሲ ልማት እና ስትራቴጂካዊ ዕቅድ።" },
    directions: { en: "Take elevator to Floor 4, turn left. Room 404 at the end.", am: "ሊፍት ወደ 4ኛ ፎቅ ይውሰዱ፣ ወደ ግራ ይታጠፉ። ክፍል 404 በመጨረሻ ላይ ነው።" },
    services: { en: ["Policy research", "Strategy formulation", "Policy analysis", "Impact assessment"], am: ["የፖሊሲ ምርምር", "ስትራቴጂ ቅረፃ", "የፖሊሲ ትንታኔ", "ተፅዕኖ ምዘና"] },
  },
  { id: 17,
    name: { en: "National Research & Development", am: "ብሔራዊ ምርምር እና ልማት" },
    description: { en: "National R&D strategy and coordination.", am: "ብሔራዊ R&D ስትራቴጂ እና ቅንጅት።" },
    directions: { en: "Take elevator to Floor 5. Room 503 near the staircase.", am: "ሊፍት ወደ 5ኛ ፎቅ ይውሰዱ። ክፍል 503 ከደረጃው አጠገብ ነው።" },
    services: { en: ["R&D strategy", "Research funding", "Innovation policy", "Technology assessment"], am: ["R&D ስትራቴጂ", "የምርምር ፋይናንስ", "የፈጠራ ፖሊሲ", "የቴክኖሎጂ ምዘና"] },
  },
  // SECTOR 5: HR & Competency
  { id: 18,
    name: { en: "Competency & HR Management", am: "ብቃት እና ሰው ሃብት አስተዳደር" },
    description: { en: "Human resource management and competency development.", am: "የሰው ሃብት አስተዳደር እና ብቃት ልማት።" },
    directions: { en: "Take elevator to Floor 3, turn right. Room 302 near the meeting room.", am: "ሊፍት ወደ 3ኛ ፎቅ ይውሰዱ፣ ወደ ቀኝ ይታጠፉ። ክፍል 302 ከስብሰባ አዳራሹ አጠገብ ነው።" },
    services: { en: ["Recruitment", "Training programs", "Performance evaluation", "Employee relations"], am: ["ምልምልና ቅጥር", "የሥልጠና ፕሮግራሞች", "የአፈፃፀም ግምገማ", "የሠራተኛ ግንኙነት"] },
  },
  { id: 19,
    name: { en: "Women & Social Resources", am: "ሴቶች እና ማህበራዊ ሀብቶች" },
    description: { en: "Women's empowerment and social resource management.", am: "የሴቶች ብቃት ማጎልበቻ እና ማህበራዊ ሀብት አስተዳደር።" },
    directions: { en: "Take elevator to Floor 4. Room 403 next to Procurement.", am: "ሊፍት ወደ 4ኛ ፎቅ ይውሰዱ። ክፍል 403 ከግዥ ክፍል አጠገብ ነው።" },
    services: { en: ["Women's programs", "Social support", "Gender equality", "Capacity building"], am: ["የሴቶች ፕሮግራሞች", "ማህበራዊ ድጋፍ", "የ양性ፆታ እኩልነት", "አቅም ግንባታ"] },
  },
  // SECTOR 6: Operations & Services
  { id: 20,
    name: { en: "General Services Executive", am: "አጠቃላይ አገልግሎቶች ሥራ አስፈጻሚ" },
    description: { en: "General services and facility management.", am: "አጠቃላይ አገልግሎቶች እና ህንፃ አስተዳደር።" },
    directions: { en: "Take elevator to Floor 3, turn left. Room 303 at the end.", am: "ሊፍት ወደ 3ኛ ፎቅ ይውሰዱ፣ ወደ ግራ ይታጠፉ። ክፍል 303 በመጨረሻ ላይ ነው።" },
    services: { en: ["Facility management", "Maintenance", "Cleaning services", "Security coordination"], am: ["ህንፃ አስተዳደር", "ጥገና", "የጽዳት አገልግሎቶች", "ደህንነት ቅንጅት"] },
  },
  { id: 21,
    name: { en: "Facility Operations Executive", am: "የህንፃ ሥራ አፈጻጸም ሥራ አስፈጻሚ" },
    description: { en: "Building operations and facility coordination.", am: "የህንፃ ሥራዎች እና ተቋም ቅንጅት።" },
    directions: { en: "Take elevator to Floor 3. Room 303 is shared office.", am: "ሊፍት ወደ 3ኛ ፎቅ ይውሰዱ። ክፍል 303 የጋራ ቢሮ ነው።" },
    services: { en: ["Building operations", "Utility management", "Space allocation", "Asset management"], am: ["የህንፃ ሥራዎች", "የመገልገያ አስተዳደር", "ቦታ ምደባ", "ንብረት አስተዳደር"] },
  },
  { id: 22,
    name: { en: "Registry Office", am: "የመዝገብ ቤት" },
    description: { en: "Document registry and records management.", am: "ሰነዶች ምዝገባ እና መዛግብት አስተዳደር።" },
    directions: { en: "Enter Building B. Registry Office is first door on left. Room 110.", am: "ህንፃ B ይግቡ። የምዝገባ ቢሮ በግራ በኩል የመጀመሪያው ክፍል ነው። ክፍል 110።" },
    services: { en: ["Document registration", "Record keeping", "File management", "Document retrieval"], am: ["ሰነዶችን ምዝገባ", "መዝገብ አያያዝ", "ፋይል አስተዳደር", "ሰነዶችን ማውጣት"] },
  },
  // SECTOR 7: Digital & ICT
  { id: 23,
    name: { en: "ICT Director", am: "የICT ዳይሬክቶሬት" },
    description: { en: "ICT services and digital infrastructure.", am: "የICT አገልግሎቶች እና ዲጂታል መሠረተ ልማት።" },
    directions: { en: "Take elevator to Floor 1, turn left. Room 105 is third door.", am: "ሊፍት ወደ 1ኛ ፎቅ ይውሰዱ፣ ወደ ግራ ይታጠፉ። ክፍል 105 ሦስተኛው ክፍል ነው።" },
    services: { en: ["Network services", "IT support", "System development", "Digital infrastructure"], am: ["የኔትወርክ አገልግሎቶች", "የIT ድጋፍ", "ስርዓት ልማት", "ዲጂታል መሠረተ ልማት"] },
  },
  { id: 24,
    name: { en: "E-Electronics & E-Government", am: "ኤሌክትሮኒክስ እና ኢ-መንግሥት" },
    description: { en: "E-government services and digital transformation.", am: "የኢ-መንግሥት አገልግሎቶች እና ዲጂታል ለውጥ።" },
    directions: { en: "Enter Building B, first floor. Room 115 at the end of corridor.", am: "ህንፃ B ይግቡ፣ 1ኛ ፎቅ። ክፍል 115 በኮሪደሩ መጨረሻ ላይ ነው።" },
    services: { en: ["E-service delivery", "Digital platform management", "Online services", "Digital transformation"], am: ["ኢ-አገልግሎት አሰጣጥ", "ዲጂታል ፕላትፎርም አስተዳደር", "የኦንላይን አገልግሎቶች", "ዲጂታል ለውጥ"] },
  },
  { id: 25,
    name: { en: "ICT & Digital Economy Deputy", am: "ICT እና ዲጂታል ኢኮኖሚ ምክትል" },
    description: { en: "Digital economy strategy and implementation.", am: "የዲጂታል ኢኮኖሚ ስትራቴጂ እና አፈፃፀም።" },
    directions: { en: "Enter Building B, take stairs to Floor 2. Room 205 on the right.", am: "ህንፃ B ይግቡ፣ ደረጃ ወደ 2ኛ ፎቅ ይውሰዱ። ክፍል 205 በቀኝ በኩል ነው።" },
    services: { en: ["Digital economy policy", "ICT strategy", "Innovation programs", "Digital inclusion"], am: ["የዲጂታል ኢኮኖሚ ፖሊሲ", "ICT ስትራቴጂ", "የፈጠራ ፕሮግራሞች", "ዲጂታል ተሳትፎ"] },
  },
  // SECTOR 8: Support Services
  { id: 26,
    name: { en: "Data Center", am: "የዳታ ማዕከል" },
    description: { en: "Ministry data center and server infrastructure.", am: "የሚኒስቴሩ ዳታ ማዕከል እና ሰርቨር መሠረተ ልማት።" },
    directions: { en: "Take elevator to Ground Floor. Data center at the end of corridor.", am: "ሊፍት ወደ ምድር ፎቅ ይውሰዱ። የዳታ ማዕከሉ በኮሪደሩ መጨረሻ ላይ ነው።" },
    services: { en: ["Server management", "Data storage", "Backup services", "Disaster recovery"], am: ["ሰርቨር አስተዳደር", "ዳታ ማከማቻ", "የምትኬ አገልግሎቶች", "አደጋ ማቻቻያ"] },
  },
  { id: 27,
    name: { en: "TV Room", am: "የቴሌቪዥን ክፍል" },
    description: { en: "Media and broadcast facilities.", am: "የሚዲያ እና የስርጭት አገልግሎቶች።" },
    directions: { en: "Ground Floor Building A. TV Room is near the Data Center.", am: "ምድር ፎቅ ህንፃ A። የቴሌቪዥን ክፍሉ ከዳታ ማዕከሉ አጠገብ ነው።" },
    services: { en: ["Media production", "Broadcasting", "Video conferencing", "Recording services"], am: ["ሚዲያ ምርት", "ስርጭት", "ቪዲዮ ኮንፈረንስ", "ቅጂ አገልግሎቶች"] },
  },
  { id: 28,
    name: { en: "Conference Hall", am: "የጉባዔ አዳራሽ" },
    description: { en: "Ministry conference and meeting facilities.", am: "የሚኒስቴሩ ጉባዔ እና ስብሰባ አዳራሽ።" },
    directions: { en: "Take elevator to Floor 8. Conference Hall is the entire floor.", am: "ሊፍት ወደ 8ኛ ፎቅ ይውሰዱ። የጉባዔ አዳራሹ ሙሉ ፎቁን ይሸፍናል።" },
    services: { en: ["Conference booking", "Meeting room rental", "Event coordination", "Catering services"], am: ["ጉባዔ ቦታ ማስያዝ", "የስብሰባ ክፍል ኪራይ", "ዝግጅት ቅንጅት", "የምግብ አቅርቦት"] },
  },
];

async function run() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("✅ Connected to MongoDB");

  for (const d of amharicData) {
    const result = await Department.findOneAndUpdate(
      { id: d.id },
      {
        $set: {
          name:        d.name,
          description: d.description,
          directions:  d.directions,
          services:    d.services,
        },
      },
      { new: true }
    );
    if (result) {
      console.log(`✅ Dept ${d.id}: ${d.name.en}`);
    } else {
      console.log(`⚠️  Dept ${d.id} not found in DB — skipping`);
    }
  }

  await mongoose.disconnect();
  console.log("\n🎉 All department Amharic translations seeded!");
}

run().catch((e) => { console.error(e); process.exit(1); });
